#!/bin/bash

cp vimrc ~/.vimrc
cp screenrc ~/.screenrc
cp profile ~/.profile
ln -sf ~/.profile ~/.bash_profile
ln -sf ~/.profile ~/.zprofile
cp gitconfig ~/.gitconfig
cp gitignore ~/.gitignore
mkdir -p ~/.profile.d
cp git-completion.bash ~/.profile.d/
cp zshrc ~/.zshrc

mkdir -p ~/software 
pushd ~/software
if [ ! -d apache-maven-3.3.9 ]; then
  curl -O http://apache.mirrors.ionfish.org/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
  tar xvfz apache-maven-3.3.9-bin.tar.gz
echo "PATH=\$PATH:~/software/apache-maven-3.3.9/bin" >> ~/.profile
fi
popd
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install haskell-stack


git submodule init && git submodule update
git config --global core.excludesfile ~/.gitignore
pushd github/zsh-git-prompt/
stack setup
stack build && stack install
popd

mkdir -p ~/.vim/autoload 
mkdir -p ~/.vim/bundle 

cp github/vim-pathogen/autoload/pathogen.vim ~/.vim/autoload/pathogen.vim 

cp -R github/solarized/vim-colors-solarized ~/.vim/bundle/
[[ "$SHELL" != "/bin/zsh" ]] && chsh -s /bin/zsh
