#!/bin/bash

cp vimrc ~/.vimrc
cp screenrc ~/.screenrc
cp profile ~/.profile
cp gitconfig ~/.gitconfig
cp gitignore ~/.gitignore

mkdir -p ~/software 
pushd ~/software
curl -O http://apache.mirrors.ionfish.org/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
tar xvfz apache-maven-3.3.9-bin.tar.gz
echo "PATH=\$PATH:~/software/apache-maven-3.3.9/bin" >> ~/.profile
popd


git submodule init && git submodule update

mkdir -p ~/.vim/autoload 
mkdir -p ~/.vim/bundle 

cp github/vim-pathogen/autoload/pathogen.vim ~/.vim/autoload/pathogen.vim 

cp -R github/solarized/vim-colors-solarized ~/.vim/bundle/
