#!/bin/bash

cp vimrc ~/.vimrc
cp screenrc ~/.screenrc
cp profile ~/.profile
cp gitconfig ~/.gitconfig
cp gitignore ~/.gitignore

git submodule init && git submodule update

mkdir -p ~/.vim/autoload 
mkdir -p ~/.vim/bundle 

cp github/vim-pathogen/autoload/pathogen.vim ~/.vim/autoload/pathogen.vim 

cp -R github/solarized/vim-colors-solarized ~/.vim/bundle/
